import type { TripStatus } from "../api/tripsApi";

export const labels = {
  appName: "RideOps",

  dashboard: "לוח בקרה",
  trips: "נסיעות",
  createTrip: "הזמנת נסיעה",
  home: "בית",
  logout: "התנתקות",

  operationsDashboard: "מערכת ניהול הסעות",
  overview: "סקירה כללית של פעילות המערכת",

  pendingApproval: "ממתינות לאישור",
  approvedTrips: "נסיעות מאושרות",
  rejectedTrips: "נסיעות שנדחו",
  cancelledTrips: "נסיעות שבוטלו",
  tripsToday: "נסיעות היום",
  tripsThisMonth: "נסיעות החודש",
  activeClients: "לקוחות פעילים",

  pendingDescription: "נסיעות שממתינות לאישור החברה",
  approvedDescription: "נסיעות שאושרו על ידי החברה",
  rejectedDescription: "נסיעות שנדחו על ידי החברה",
  cancelledDescription: "נסיעות שבוטלו",
  todayDescription: "נסיעות המתוכננות להיום",
  monthDescription: "נסיעות המתוכננות לחודש הנוכחי",
  clientsDescription: "לקוחות פעילים במערכת",

  tripsPageTitle: "נסיעות",
  tripsPageDescription: "צפייה, חיפוש וסינון של הזמנות נסיעה",
  search: "חיפוש",
  searchPlaceholder: "יעד, כתובת איסוף, הערות...",
  status: "סטטוס",
  all: "הכול",
  sortBy: "מיון לפי",
  pickupDate: "תאריך איסוף",
  createdAt: "תאריך יצירה",
  order: "סדר",
  ascending: "עולה",
  descending: "יורד",
  applyFilters: "החל סינון",

  exportApproved: "ייצוא מאושרות",
  exporting: "מייצא...",
  exportSuccess: "הנסיעות המאושרות יוצאו בהצלחה",
  exportFailed: "ייצוא הנסיעות נכשל",

  tripNumber: "מס׳ נסיעה",
  client: "לקוח",
  pickupTime: "זמן איסוף",
  pickup: "איסוף",
  destination: "יעד",
  passengers: "נוסעים",
  duplicate: "כפילות",
  yes: "כן",
  no: "לא",

  loadingTrips: "טוען נסיעות...",
  failedToLoadTrips: "טעינת הנסיעות נכשלה",
  noTripsFound: "לא נמצאו נסיעות",
  noTripsDescription: "נסה לשנות את הסינון או ליצור הזמנת נסיעה חדשה.",
  previous: "הקודם",
  next: "הבא",
  page: "עמוד",
  of: "מתוך",

  tripDetails: "פרטי נסיעה",
  workflow: "תהליך טיפול",
  pickupDateTime: "תאריך ושעת איסוף",
  pickupLocation: "נקודת איסוף",
  notes: "הערות",
  duplicateWarning: "חשד לכפילות",
  exported: "יוצאה לאקסל",
  exportedAt: "תאריך ייצוא",
  createdBy: "נוצרה על ידי",
  approvedAt: "אושרה בתאריך",
  approvedBy: "אושרה על ידי",
  rejectedAt: "נדחתה בתאריך",
  rejectedBy: "נדחתה על ידי",
  rejectionReason: "סיבת דחייה",
  cancelledAt: "בוטלה בתאריך",
  cancelledBy: "בוטלה על ידי",
  backToTrips: "חזרה לנסיעות",
  tripNotFound: "הנסיעה לא נמצאה",
  tripNotFoundDescription: "הנסיעה לא קיימת או שאין לך הרשאה לצפות בה.",
  duplicateWarningMessage:
    "ייתכן שהנסיעה הזו כפולה. מומלץ לבדוק את התאריך, הלקוח והיעד.",

  approveTrip: "אשר נסיעה",
  rejectTrip: "דחה נסיעה",
  cancelTrip: "בטל נסיעה",
  approving: "מאשר...",
  rejecting: "דוחה...",
  cancelling: "מבטל...",
  keepTrip: "השאר נסיעה",

  approvedSuccess: "הנסיעה אושרה בהצלחה",
  approvedError: "לא הצלחנו לאשר את הנסיעה",
  rejectedSuccess: "הנסיעה נדחתה בהצלחה",
  rejectedError: "לא הצלחנו לדחות את הנסיעה",
  cancelledSuccess: "הנסיעה בוטלה בהצלחה",
  cancelledError: "לא הצלחנו לבטל את הנסיעה",
  loadTripError: "לא הצלחנו לטעון את פרטי הנסיעה",

  cancelTripTitle: "ביטול נסיעה",
  cancelTripDescription:
    "האם אתה בטוח שברצונך לבטל את הנסיעה? הסטטוס ישתנה לבוטלה.",
  rejectTripTitle: "דחיית נסיעה",
  rejectTripDescription:
    "יש להזין סיבת דחייה. הלקוח יוכל לראות את הסיבה.",
  rejectionReasonPlaceholder: "סיבת הדחייה...",
  rejectionReasonValidation: "סיבת הדחייה חייבת להכיל לפחות 2 תווים.",
};

export const tripStatusLabels: Record<TripStatus, string> = {
  PENDING_APPROVAL: "ממתינה לאישור",
  APPROVED: "מאושרת",
  REJECTED: "נדחתה",
  CANCELLED: "בוטלה",
};