export const labels = {
  appName: "RideOps",

  dashboard: "לוח בקרה",
  trips: "נסיעות",
  createTrip: "הזמנת נסיעה",
  home: "בית",
  logout: "התנתקות",

  operationsDashboard: "מערכת ניהול הסעות",
  overview: "סקירה כללית של פעילות המערכת",

  pendingApproval: "ממתינות לאישור",
  approvedTrips: "נסיעות מאושרות",
  rejectedTrips: "נסיעות שנדחו",
  cancelledTrips: "נסיעות שבוטלו",
  tripsToday: "נסיעות היום",
  tripsThisMonth: "נסיעות החודש",
  activeClients: "לקוחות פעילים",

  pendingDescription: "נסיעות שממתינות לאישור החברה",
  approvedDescription: "נסיעות שאושרו על ידי החברה",
  rejectedDescription: "נסיעות שנדחו על ידי החברה",
  cancelledDescription: "נסיעות שבוטלו",
  todayDescription: "נסיעות המתוכננות להיום",
  monthDescription: "נסיעות המתוכננות לחודש הנוכחי",
  clientsDescription: "לקוחות פעילים במערכת",

  tripsPageTitle: "נסיעות",
  tripsPageDescription: "צפייה, חיפוש וסינון של הזמנות נסיעה",
  search: "חיפוש",
  searchPlaceholder: "יעד, כתובת איסוף, הערות...",
  status: "סטטוס",
  all: "הכול",
  sortBy: "מיון לפי",
  pickupDate: "תאריך איסוף",
  createdAt: "תאריך יצירה",
  order: "סדר",
  ascending: "עולה",
  descending: "יורד",
  applyFilters: "החל סינון",

  exportApproved: "ייצוא מאושרות",
  exporting: "מייצא...",
  exportSuccess: "הנסיעות המאושרות יוצאו בהצלחה",
  exportFailed: "ייצוא הנסיעות נכשל",

  tripNumber: "מס׳ נסיעה",
  client: "לקוח",
  pickupTime: "זמן איסוף",
  pickup: "איסוף",
  destination: "יעד",
  passengers: "נוסעים",
  duplicate: "כפילות",
  yes: "כן",
  no: "לא",

  loadingTrips: "טוען נסיעות...",
  failedToLoadTrips: "טעינת הנסיעות נכשלה",
  noTripsFound: "לא נמצאו נסיעות",
  noTripsDescription: "נסה לשנות את הסינון או ליצור הזמנת נסיעה חדשה.",
  previous: "הקודם",
  next: "הבא",
  page: "עמוד",
  of: "מתוך",
};